name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build
        run: dotnet build CloudSoft/CloudSoft.sln --configuration Release
        env:
          MongoDb__ConnectionString: ${{ secrets.MONGODB_CONNECTION_STRING || 'mongodb://localhost:27017/defaultdb' }}
          AzureBlob__ConnectionString: ${{ secrets.AZURE_BLOB_CONNECTION_STRING || 'DefaultAzureBlobPlaceholder' }}
          FeatureFlags__UseMongoDb: "true"
          FeatureFlags__UseAzureStorage: "true"

      - name: Publish
        run: dotnet publish CloudSoft/CloudSoft.csproj --configuration Release -o publish_output
        env:
          MongoDb__ConnectionString: ${{ secrets.MONGODB_CONNECTION_STRING || 'mongodb://localhost:27017/defaultdb' }}
          AzureBlob__ConnectionString: ${{ secrets.AZURE_BLOB_CONNECTION_STRING || 'DefaultAzureBlobPlaceholder' }}
          FeatureFlags__UseMongoDb: "true"
          FeatureFlags__UseAzureStorage: "true"

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
        shell: bash

      - name: Deploy via SCP
        run: |
          scp -o StrictHostKeyChecking=no -r publish_output/* azureuser@10.0.3.4:/home/azureuser/app/
        shell: bash
