name: Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    # Another comment to make a change
    # Anv채nd 'self-hosted' om du har en egen runner i ditt s채kra n채tverk,
    # annars kan du byta till 'ubuntu-latest' om du vill anv채nda en GitHub-hosted runner.
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.201'

      - name: Build
        run: dotnet build --configuration Release
        env:
          MongoDb__ConnectionString: ${{ secrets.MONGODB_CONNECTION_STRING }}
          AzureBlob__ConnectionString: ${{ secrets.AZURE_BLOB_CONNECTION_STRING }}
          FeatureFlags__UseMongoDb: "true"
          FeatureFlags__UseAzureStorage: "true"

      - name: Publish
        run: dotnet publish --configuration Release -o publish_output
        env:
          MongoDb__ConnectionString: ${{ secrets.MONGODB_CONNECTION_STRING }}
          AzureBlob__ConnectionString: ${{ secrets.AZURE_BLOB_CONNECTION_STRING }}
          FeatureFlags__UseMongoDb: "true"
          FeatureFlags__UseAzureStorage: "true"

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
        shell: bash

      - name: Deploy via SCP
        run: |
          scp -o StrictHostKeyChecking=no -r publish_output/* azureuser@<server-ip>:/home/azureuser/app/
        shell: bash